trigger:
- master
pool:
  vmImage: ubuntu-latest
steps:
- checkout: self 
  persistCredentials: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      <#
      Version: 1.0
      #>      
      
      
      #################################################################################################
      ########################################### Start ###############################################
      #################################################################################################
     
        #Define outputs
        $IntuneOutputFQDN = "./IntuneNetworkEndpoints-FQDN.txt"
        $IntuneOutputIPs = "./IntuneNetworkEndpoints-IPs.txt"
        $MicrosoftGeneralEndpoints = "MicrosoftGeneralEndpoints.txt"

        #Query MEM endpoint FQDN and save to file
        (invoke-restmethod -Uri ("https://endpoints.office.com/endpoints/WorldWide?ServiceAreas=MEM`&`clientrequestid=" + ([GUID]::NewGuid()).Guid)) | ?{$_.ServiceArea -eq "MEM" -and $_.urls} | select -unique -ExpandProperty urls | Out-File -FilePath $IntuneOutputFQDN

        #Query MEM endpoint IPs and save to file
        (invoke-restmethod -Uri ("https://endpoints.office.com/endpoints/WorldWide?ServiceAreas=MEM`&`clientrequestid=" + ([GUID]::NewGuid()).Guid)) | ?{$_.ServiceArea -eq "MEM" -and $_.ips} | select -unique -ExpandProperty ips | Out-File -FilePath $IntuneOutputIPs

        #Query all Microsoft endpoints and save to file
        (invoke-restmethod -Uri ("https://endpoints.office.com/endpoints/WorldWide?clientrequestid=" + ([GUID]::NewGuid()).Guid)) | select -unique -ExpandProperty urls -ErrorAction SilentlyContinue | Out-File -FilePath $MicrosoftGeneralEndpoints

      dir

- script: |
    git config --global user.email "automation@azuredevops.com"
    git config --global user.name "thenikk"
    git checkout -b main
    git add -A
    git commit -m "deployment $(Build.BuildNumber)"
    git push --set-upstream origin main 
  displayName: Git
  workingDirectory: $(System.DefaultWorkingDirectory)